### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [imperva/terraform-provider-incapsula#1]
Hey Team, 👋 My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! All acceptance tests are passing with 95% code coverage. Amazing! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `725366a`.

There are a number of files that must be added in order for the provider to function in the Terraform native ecosystem.  
- [x] The GNUmakefile is pretty standard across all Terraform providers, feel free to copy the [NULL provider makefile](https://github.com/terraform-providers/terraform-provider-tls/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=incapsula
- [x] There are four bash scripts in a scripts/ that are used in different processes of testing and release, these can all be copied from the [NULL provider](https://github.com/terraform-providers/terraform-provider-null/tree/master/scripts) 
- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the nexted release should be tagged as “(Unreleased)” and will then be updated with a date by the release-bot. 
- [x] All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)
- [x] All of the Terraform Providers use a [Mozilla Public License 2.0](https://github.com/terraform-providers/terraform-provider-null/blob/master/LICENSE), would you be able to update your MIT license to MPL2.0?
- [x] You will need to build website documentation for reach resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [NULL provider](https://github.com/terraform-providers/terraform-provider-null) website docs for help. (I can also help with this if needed.)
- [x] There is a standard README.md for of the official provider, see [Null provider README.md](https://github.com/terraform-providers/terraform-provider-null/blob/master/README.md)

Once all these items have been address, the next phase will be a deep technical review from a member of HashiCorp’s Terraform ecosystem engineering team. To prepare you for that, they have written out a few items that are seen as provider code expectation and conventions:

 - [x] resource filename matches convention `resource_providername_resource_name.go`
 - [x] data source filename matches convention `data_source_providername_resource_name.go`
 - [x] we always let `d.Set()` to dereference pointers safely to avoid crashes, i.e. there's nothing like `d.Set(*variable)`
 - [x] flatteners and expanders are in `structures.go` + tests in `structures_test.go`
 - [x] any validation functions longer than a few lines are in `validators.go` + tests in `validators_test.go`
 - [x] `d.Set()` is called in any C/R/U/D for all available fields unless they're Computed-only (i.e. there are no orphans)
 - [x] all of `d.Set()`, `d.Get()`, `d.GetOk()`, `d.GetChange()` etc. use real field names (i.e. no typos)
 - [x] `d.Set()` is _always_ error-checked if it’s set, list or map
 - [x] `d.Set()` is _never_ error-checked if it's primitive data type (string, int, float, bool)
 - [x] Resource uses either `Read` or `Exists` function to remove resource from state if it's gone
 - [x] `d.Partial()` & `d.SetPartial()` are used any time there's more than 1 API call used to create or update a resource.
 - [x] `schema.ForceNew` is used for any field that is not updatable
 - [x] all field names are `lowercase_underscore`
 - [x] where possible data source fields match resource (e.g. when referencing `aws_instance` user shouldn't need to change anything - just add `data.` prefix)
 - [x] Constants are used if there are available in the upstream SDK (e.g. for status codes)
 - [x] `[INFO]` log message at least 2 per each C/R/U/D - e.g. creating (input), created (output)
 - [x] The provider code does not `panic`, always returns errors

Let me know if you have any questions about this.

**Comment by anandkunal** [comment]
Hi @cgriggs01 - all of the above is done. I'm having an issue with the website not coming up - I'm specifically getting an error of not found when viewing the provider's documentation. Can you take a look and point me in the right direction? All of the content is there and ready to go. Thanks!

**Comment by cgriggs01** [comment]
I have a few resources that will hopefully help you to develop, preview and validate your Terraform provider website documentation. 

The Terraform.io website uses our terraform-website/ repository that is used as the middleman to sync all the terraform and provider documentation from all of their own repositories. To deploy the website locally follow the steps outlined in the README.

Once you've synced the current submodules there are 3 more steps required for adding you provider
Add the Incapsula provider as a submodule to the terraform-website/ directory with:
"git submodule add -b master https://github.com/inperva/terraform-provider-incapsula ext/providers/incapsula"

Then you'll have to create two symbolic links to this module, first change to the working directory terraform-website/content/source/docs/providers/ the run:
"ln -s ../../../../ext/providers/incapsula/website/docs incapsula"

And then change to the working directory to "terraform-website/content/source/layouts/" to run:
"ln -s ../../../ext/providers/incapsula/website/incapsula.erb"

After those additions, you can then run the "make website" target to spin up the website using Docker desktop.

**Comment by cgriggs01** [comment]
Hi @anandkunal,
One more thing that needs to be changed. The `layouts/` directory should be removed and its contents moved into the `docs/`. This is required for deploying the website documentation. 
Thanks!

**Comment by anandkunal** [comment]
Hi @cgriggs01 - I'm not following your last comment. I'm looking at the `null` provider and some of the others and it looks like doc structure in this repo is consistent with the others. Am I missing something?

**Comment by cgriggs01** [comment]
Hey @anandkunal,

Looks like you've already fixed the issue I had raised. You can disregard it.

**Comment by anandkunal** [comment]
Hi @cgriggs01 - we're ready to go on this end. Can you kick off the review? We'll hold off on bringing in new resources (we've got a big PR waiting) until we get through the review.

**Comment by cgriggs01** [comment]
Hi @anandkunal,

Thanks for the note

I'll start the second review today.

**Comment by cgriggs01** [comment]
Closing this issue since I've created another issue https://github.com/imperva/terraform-provider-incapsula/issues/9 for the final review
