### ISSUE TITLE
Support for client certificates in the provider?

### ISSUE THREAD

**Issue by plambrechtsenanz** [imperva/terraform-provider-incapsula#102]
Is there any plans to add support for Client Certificates into the provider?

As per:
https://docs.imperva.com/bundle/cloud-application-security/page/manage-client-certificate.htm
and
https://docs.imperva.com/bundle/cloud-application-security/page/certificate-api-definition.htm

The following tasks cannot be performed by the provide:

- Upload Client Certificates as per Client CA Certificates Configuration -> Upload New

Set any of these values on the site:
- Require client certificate
- Send client certificate details to origin server
- Specify Header name
- Specify Header value. As this has changed from being a rule you can no longer have multiple values.
- Restrict client certificate for hosts & ports enable & disable
- Restrict client certificate fingerprints

And lastly assign specific certificates uploaded in the first step to be assigned to the site.

There is support for this in the API, but it doesn't seem to have been built for the provider. Are there plans to add it?

**Comment by whathelll** [comment]
how do I upvote this?

**Comment by lfventura** [comment]
We are also needing this feature.

**Comment by katrinpolit** [comment]
Hi. This feature is currently in development and will be available in the nearest future.
