### ISSUE TITLE
WAF rules - unable do be set/changed at once

### ISSUE THREAD

**Issue by ltylski** [imperva/terraform-provider-incapsula#106]
Hi,

It looks like it is not possible to set or update all WAF rules at once. terraform apply has to be run as many times as much rules are set.

Regards,

Lukasz

**Comment by joeymoore** [comment]
@ltylski this is why we require the parallelism flag: "terraform apply -parallelism=1"

**Comment by ltylski** [comment]
Oh, I've missed that...
