### ISSUE TITLE
Certificate upload example / documentation not given.

### ISSUE THREAD

**Issue by AirCombat** [imperva/terraform-provider-incapsula#11]
Hi,

We only use our own certificates (for a number of reasons) but I cannot see an example / documentation for the functionality normally provided by this API: https://my.incapsula.com/api/prov/v1/sites/customCertificate/upload

I also could not see the equivelent in resource_incapsula_site.go

This is core functionality for us that would prevent us moving from our scripts to the new provider.

Thanks

**Comment by banderson0421** [comment]
Hi,

Thank you for sharing this!  Custom certificates have now been implemented and sample configs are present in the examples folder.  Please let us know if you run into any issues in testing or using this.  Thanks!

**Comment by AirCombat** [comment]
I will test and confirm shortly when we have a new site to deploy.

**Comment by anandkunal** [comment]
Hi @AirCombat - we've added documentation in the `custom_certificate.html.markdown` as well as created an example. I'm going to close this out. BTW, you'll notice a bunch of updates that just landed in master, including a move to APIv2 for Incap Rules.
