### ISSUE TITLE
Redirect HTTP requests to HTTPS requests by sending an HTTP 301 response

### ISSUE THREAD

**Issue by brunooliveiramac** [imperva/terraform-provider-incapsula#110]
Hi all,
sorry if this is not the right place, but we couldn't find any option on the provider to have this option enabled to our website:

![image](https://user-images.githubusercontent.com/10716628/137486618-fed80af9-2b67-4221-b754-7e950bd76c38.png)

Is there any way to have this on any provider parameters, or is this not possible so far?

**Comment by brunooliveiramac** [comment]
Thanks @joeymoore 
We are going to test that

**Comment by StingeyNinja** [comment]
For anyone else reviewing this thread in future, this is now available as an application delivery rule:
https://registry.terraform.io/providers/imperva/incapsula/3.15.1/docs/resources/application_delivery#redirect_http_to_https
