### ISSUE TITLE
Creating site with HTTPS on 

### ISSUE THREAD

**Issue by ltylski** [imperva/terraform-provider-incapsula#111]
Hi,

Error status code 401 from Incapsula service when updating Incap Performance Settings for Site ID xxxxx: {"res":3015,"res_message":"Internal error","debug_info":{"Error":"Cannot enable HTTPS caching for non-SSL sites","id-info":"13008"}}

That's what I got during new site creation. I do have a resource to set up custom certificate but it is created later as it requires site id.

This is my resource:

resource "incapsula_site" "site" {
  domain                                   = "xxx.aaa.com"
  acceleration_level                       = "aggressive"
  active                                   = "active"
  data_storage_region                      = "EU"
  hashing_enabled                          = false
  naked_domain_san                         = true
  perf_client_comply_no_cache              = false
  perf_client_enable_client_side_caching   = true
  perf_client_send_age_header              = false
  perf_key_comply_vary                     = false
  perf_key_unite_naked_full_cache          = false
  perf_mode_https                          = "dont_include_html"
  perf_mode_level                          = "smart"
  perf_mode_time                           = 300
  perf_response_cache_300x                 = false
  perf_response_cache_404_enabled          = false
  perf_response_cache_404_time             = 0
  perf_response_cache_empty_responses      = false
  perf_response_cache_http_10_responses    = false
  perf_response_cache_response_header_mode = "custom"
  perf_response_cache_response_headers = [
    "Access-Control-Allow-Origin",
    "Vary",
  ]
  perf_response_cache_shield       = true
  perf_response_stale_content_mode = "adaptive"
  perf_response_stale_content_time = 0
  perf_ttl_prefer_last_modified    = false
  perf_ttl_use_shortest_caching    = false
  seal_location                    = "api.seal_location.none"
  wildcard_san                     = true

  timeouts {}
}

site is being created partially. When I set custom certificate using web UI, import the site and then run it once again, it works.

What am I doing wrong?

Lukasz

**Comment by BrachaY** [comment]
Hi @ltylski 
Is this issue still relevant?

**Comment by BrachaY** [comment]
Thanks, @ltylski for bringing it up.
Please open a support case via Imperva portal, it will ease the process of the investigation.

**Comment by BrachaY** [comment]
@ltylski have you managed to open the support case?
Do you need further assistance?
Or can I close the issue?

**Comment by ltylski** [comment]
Hi,

Yes, I did, thanks.

Pozdrawiam/Best regards,
[signature_2115582391]<https://www.genesis.com.mt/>
Lukasz Tylski
SysOps
[signature_941839569]<https://www.genesis.com.mt/>
M. +48 600087486
E. ***@***.******@***.***>


From: Bracha Yalon ***@***.***>
Date: Wednesday, 16 November 2022 at 06:06
To: imperva/terraform-provider-incapsula ***@***.***>
Cc: Lukasz Tylski ***@***.***>, Mention ***@***.***>
Subject: Re: [imperva/terraform-provider-incapsula] Creating site with HTTPS on (Issue #111)

@ltylski<https://github.com/ltylski> have you managed to open the support case?
Do you need further assistance?
Or can I close the issue?

**Comment by BrachaY** [comment]
closing the issue as it will be handled via Imperva's customer portal
