### ISSUE TITLE
Can't create site with HTTP/2 enabled

### ISSUE THREAD

**Issue by orsiberton** [imperva/terraform-provider-incapsula#115]
I am not able to create a website with the option HTTP/2 enabled.

![image](https://user-images.githubusercontent.com/13476147/139672582-78cc0cac-fc53-434d-ba04-c594ebe12f57.png)

**Comment by joeymoore** [comment]
Not as of right now. You can set this at the account level to be the default.
![image](https://user-images.githubusercontent.com/41126299/139700901-ac4f5b04-6118-4c63-b7ef-530509f7420c.png)
