### ISSUE TITLE
Provider Documentation

### ISSUE THREAD

**Issue by AirCombat** [imperva/terraform-provider-incapsula#12]
Please add documentation for the provider to docs.imperva.com including:

Index of all resource, data sources, import functionality (we have over 100 existing sites) as well as documentation on the accepted input params and outputs for each resource.

Thanks!

**Comment by mihaiturcu** [comment]
Up, hitting the same issue:
https://www.terraform.io/docs/providers/incapsula/index.html
This return a page not found.

**Comment by anandkunal** [comment]
This is only going to be available in the TF registry. Closing.
