### ISSUE TITLE
Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by rubaroca** [imperva/terraform-provider-incapsula#156]
Hi, 

I am trying to apply 8 rules from my terraform project but some rules are not created.

`
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.imperva_rules.incapsula_incap_rule.this["Ignore_public_image_waiting.gif"], provider
│ "provider[\"registry.terraform.io/imperva/incapsula\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
` 

This error force me to reapply "n" time until all rules are created. 

Thanks, 
BR

**Comment by BrachaY** [comment]
Are you working with paallelism=1 as we recommend?
If not, please give it a try first.

**Comment by rubaroca** [comment]
Hi @BrachaY,
Setting -parallelism=1 works fine. 
Thanks.
