### ISSUE TITLE
Error: Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by Zack-Watt** [imperva/terraform-provider-incapsula#159]
Error: Provider produced inconsistent result after apply
When applying changes to incapsula_waf_security_rule, provider "provider[\"registry.terraform.io/imperva/incapsula\"]" produced an unexpected new value: Root resource was present, but now absent. This is a bug in the provider, which should be reported in the provider's own issue tracker.

Updated version to 3.5.1, also failed on version 3.2.2
```terraform  
required_providers {
    incapsula = {
      source  = "imperva/incapsula"
      version = "3.5.1"
    }
```
Example:  

```terraform
resource "incapsula_waf_security_rule" "resource-name" {
  site_id = incapsula_site.resource-name.id
  rule_id = "integration.api.threats.backdoor"
  security_rule_action = "api.threats.action.quarantine_url" # (api.threats.action.quarantine_url (default) | api.threats.action.alert | api.threats.action.disabled | api.threats.action.quarantine_url)
}
```

**Comment by BrachaY** [comment]
@Zack-Watt Please use parallelism=1 and see if the issue is reprodeced

**Comment by Zack-Watt** [comment]
@BrachaY 
Wasn't positive on what agent we're running. Pretty sure we're running the cloud agent. Attempted both methods in environment variables just to make sure though. All plans produced the same plan of adding our 14 rules, and then same error we've seen when attempting to run the apply.


[»](https://www.terraform.io/cloud-docs/workspaces/variables#parallelism)Parallelism
You can use the TFE_PARALLELISM environment variable when your infrastructure providers produce errors on concurrent operations or use non-standard rate limiting. The TFE_PARALLELISM variable sets the -parallelism=<N> flag for terraform plan and terraform apply ([more about parallelism](https://www.terraform.io/internals/graph#walking-the-graph)). Valid values are between 1 and 256, inclusive, and the default is 10. Terraform Cloud Agents do not support TFE_PARALLELISM, but you can specify flags as environment variables directly via TF_CLI_ARGS_name. In these cases, use TF_CLI_ARGS_plan="-parallelism=<N>" or TF_CLI_ARGS_apply="-parallelism=<N>" instead.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/98503240/167484370-0e4d4364-af44-4b79-a4f6-b06b4613f903.png">

Anything else that I should try?

**Comment by BrachaY** [comment]
@Zack-Watt 
Please attach the provider logs in debug mode - add TF_LOG=DEBUG before the terraform apply command

**Comment by Zack-Watt** [comment]
I've attached plan/apply logs.
[run-bqRWkQzRTCRDbHk1-plan-log.txt](https://github.com/imperva/terraform-provider-incapsula/files/8702286/run-bqRWkQzRTCRDbHk1-plan-log.txt)
[run-bqRWkQzRTCRDbHk1-apply-log.txt](https://github.com/imperva/terraform-provider-incapsula/files/8702287/run-bqRWkQzRTCRDbHk1-apply-log.txt)

Here are plan/apply logs. Let me know if there is anything else I can provide.

**Comment by BrachaY** [comment]
Hi @Zack-Watt 
For some reason you added the prefix "integration" to all rule ids. remove it and it will work for you.
In addition, we will fix the bug that let you put this id in the first place - the id should be validated according to a close list of ids.

**Comment by Zack-Watt** [comment]
that worked. Looks like we added that for our integration environment as a naming convention and didn't realize that wasn't meant to be changed.

Thank you for the help.
