### ISSUE TITLE
Spin-off SDK to separate repository?

### ISSUE THREAD

**Issue by yannh** [imperva/terraform-provider-incapsula#20]
Hello, and thanks for this very nice Terraform provider! It contains a great Go SDK for Incapsula, which could be used as a library by other projects to talk to the Incapsula API.
For example, I am currently writing a Prometheus exporter for Incapsula traffic statistics, and would love to extend the SDK to add more calls - however I m not sure how useful it would be to the terraform provider.

Do you think it would be practical to move the SDK part of this repository (incapsula/client_*.go files) to a separate repository, that could be used with go modules, and that this project would import? I know it represents quite some work, but it might be quite useful for others to build upon - I thought I'd mention there is interest :+1: 

Thanks!

**Comment by anandkunal** [comment]
Hi @yannh - yes, that is in fact the plan. We're working with our legal team to clear things like licensing, but we will split the SDK from the provider. This will most likely come post-certification in a v2 point release (will be backwards compatible). Closing this out.
