### ISSUE TITLE
Link to the provider page in terraform.io not working

### ISSUE THREAD

**Issue by thamizarasu** [imperva/terraform-provider-incapsula#3]
The linked provider in the Terraform site for Incapsula Terraform provider information is not there. 

https://www.terraform.io/docs/providers/incapsula/index.html - 404.

**Comment by Techcadia** [comment]
The links will start functioning after #1 is completed.

**Comment by anandkunal** [comment]
Yes, we're almost there on #1. Need to get the site docs setup. The current README is the boilerplate, which is standard for all Terraform plugins.
