### ISSUE TITLE
resource "incapsula_incap_rule" does not fully support URL forwarding

### ISSUE THREAD

**Issue by adamyanlina** [imperva/terraform-provider-incapsula#306]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have replicated my issue using the latest version of the provider and it is still present.

### Terraform and Imperva provider version

terraform {
  required_version = ">= 1.1.2"

  # Central account, so we can automate R53
  backend "s3" {
    encrypt        = true
    bucket         = "central-imperva-terraform-state"
    dynamodb_table = "imperva-terraform-state-lock"
    region         = "eu-west-1"
    key            = "eu-terraform-state"
  }

  required_providers {
    incapsula = {
      source  = "imperva/incapsula"
      version = ">= 3.2"
    }
    aws = {
      version = ">= 4.30.0"
    }
  }
}

provider "aws" {
  region = "eu-west-1"

  default_tags {
    tags = {
      Environment    = "Production"
      Owner          = "ME"
      Project        = "Terraform"
      Name           = "Imperva Implementation"
      Classification = "Internal"
      Domain         = "Platform"
      Region         = "EU"
    }
  }
}

provider "incapsula" {
  api_id  = jsondecode(data.aws_secretsmanager_secret_version.imperva_secret_values.secret_string)["incapsula_api_id"]
  api_key = jsondecode(data.aws_secretsmanager_secret_version.imperva_secret_values.secret_string)["incapsula_api_key"]
}

resource "aws_dynamodb_table" "imperva-terraform-state-lock" {
  name           = "imperva-terraform-state-lock"
  hash_key       = "LockID"
  read_capacity  = 20
  write_capacity = 20

  point_in_time_recovery {
    enabled = true
  }

  server_side_encryption {
    enabled = true
  }

  attribute {
    name = "LockID"
    type = "S"
  }
}

data "aws_secretsmanager_secret" "imperva_secrets" {
  arn = "arn:aws:secretsmanager:XXX:XXXX:secret:imperva/YYYYY/XXXXXXX"
}

data "aws_secretsmanager_secret_version" "imperva_secret_values" {
  secret_id = data.aws_secretsmanager_secret.imperva_secrets.id
}

### Affected resource(s)

incapsula_incap_rule

### Terraform configuration files

```hcl
resource "incapsula_incap_rule" "endpoint_forward_rule_1" {
  name           = "endpoint_forward_rule"
  site_id        = module.site.self.site_id
  dc_id          = var.forward_site_destination # INFO: dc_id "https://second.example.com/v1/new-path"
  action         = "RULE_ACTION_FORWARD_TO_URL"
  response_code  = 301
  filter         = "Full-URL == \"https://first.example.com/v1/my/path\""
  to   = "https://second.example.com/v1/new-path"
}
```

### Debug output

│ Error: Error status code 406 from Incapsula service when adding Incap Rule for Site ID 44739572: {"res":2,"res_message":"Invalid input","debug_info":{"id-info":"999999"}}

### Expected output

I don't understand error message, How I can forward "https://first.example.com/v1/my/path" to "https://second.example.com/v1/new-path" via terraform (provider imperva/incapsula) ?

### Actual output

│ Error: Error status code 406 from Incapsula service when adding Incap Rule for Site ID 44739572: {"res":2,"res_message":"Invalid input","debug_info":{"id-info":"999999"}}

### Steps to reproduce

1. I already check my site_id, dc_id and this fields are correct
2. I ask question Chat GPT but he cannot help fix error :D
3. I find only one example about url forwarding where i don't see forwarding to another domain+path (specific path not the same original path)

**Comment by joeymoore** [comment]
Hello @adamyanlina 
First off, love the ChatGPT poke!!
If I understand you correctly and you're just trying to do a simple URL rewrite, this the dc_id is not needed.
resource "incapsula_incap_rule" "example-incap-rule-rewrite-url" {
  name = "ExampleRewriteURL"
  site_id = incapsula_site.example-site.id
  action = "RULE_ACTION_REWRITE_URL"
  filter = "Full-URL == \"/someurl\""
  from = "*"
  to = "/redirect"
  enabled = true
}
Using this doc page to refer the variables: 
https://docs.imperva.com/bundle/cloud-application-security/page/rules/create-rule.htm#Rewrite

Now, if you trying to forward this specific filter to a specific data center, then another rule for the DC forward will be needed, ref a DC_ID with data center data source.

# For a more detailed example of how to reference a data center id, look at datasource incapsula_data_center :
https://registry.terraform.io/providers/imperva/incapsula/latest/docs/data-sources/data_center

resource "incapsula_incap_rule" "example-incap-rule-fwd-to-data-center" {
  name = "Example incap rule forward to data center"
  site_id = incapsula_site.example-site.id
  action = "RULE_ACTION_FORWARD_TO_DC"
  filter = "Full-URL == \"/someurl\""
  dc_id = data.incapsula_data_center.example_content_dc.id
  enabled = true  
}

This assuming the DC is created elsewhere.
Hope this helps.

**Comment by adamyanlina** [comment]
Hi @joeymoore ! Thanks for your response!
As I wrote, I need to redirect from "https://first.example.com/v1/my/path" to "https://second.example.com/v1/new-path" (meaning forward url- addresses from `domain+path` to `another domain+anoother path`). I already tried to create a rule with the "RULE_ACTION_REWRITE_URL" action, but I can't set the `to="https://second.example.com/v1/new-path"` argument, I get an error: `│ Error: Error status code 406 from Incapsula service when adding Incap Rule for Site ID 44739572: {"res":2,"res_message":"Invalid input","debug_info":{"redirectTo":"Field must start with a wild card or slash (\"/\")","id-info":"999999"}}
`

**Comment by jonathan-el** [comment]
Hi @adamyanlina!
If you need to send a 301 redirect response then it would seem that redirect rules are better suited, e.g.:
```terraform
resource "incapsula_incap_rule" "endpoint_forward_rule_1" {
  name           = "endpoint_forward_rule"
  site_id        = module.site.self.site_id
  action         = "RULE_ACTION_REDIRECT"
  response_code  = "301"
  filter         = "URL == \"/v1/my/path\""
  to             = "https://second.example.com/v1/new-path"
}
```
Please let me know if that worked out for you.
