### ISSUE TITLE
Add a new datasource to retrieve Imperva ip addresses

### ISSUE THREAD

**Issue by bkamin29** [imperva/terraform-provider-incapsula#31]
Use this datasource to create new firewall with terraform to allow traffic from Imperva incapsula

https://support.incapsula.com/hc/en-us/articles/200627570-Whitelist-Incapsula-IP-addresses-Setting-IP-restriction-rules

**Comment by anandkunal** [comment]
Hi @bkamin29 - are you looking for us to build out a datasource that contains the the Cloud WAF IP addresses? In terms of a format, are you ok with these being in an array?

**Comment by joeymoore** [comment]
@bkamin29 depending on where you would like to apply these rules will determine how you address this.
The approach I took when locking down our k8s service(classic ELB) to Imperva IP is with HCL within the TF enterprise variable.
load_balancer_source_ranges = var.cwaf-ip

cwaf-ip = ["199.83.128.0/21","198.143.32.0/19","149.126.72.0/21","103.28.248.0/22","45.64.64.0/22","185.11.124.0/22","192.230.64.0/18","107.154.0.0/16","45.60.0.0/16","45.223.0.0/16","192.116.40.64/28","198.143.36.0/24","192.230.75.0/24","192.230.76.0/24","3.128.50.186/32","3.128.61.177/32","3.21.42.77/32"]

**Comment by bkamin29** [comment]
Hello @anandkunal @joeymoore ,

Thank you for your answers.
Yes, a datadource which give an array of Imperva IPs addresses as output will be very useful !

Today we use a static TF variable like `cwaf-ip` to authorize Imperva from our Firewalls. But having a dynamic datasource contening you IPs Addresses will be better

Benjamin

**Comment by anandkunal** [comment]
Hi @bkamin29 - understood. I'll bring this up in the roadmap - should be fairly straightforward. I'll let you know when this is available.

**Comment by bkamin29** [comment]
> Hi @bkamin29 - understood. I'll bring this up in the roadmap - should be fairly straightforward. I'll let you know when this is available.

Hello @anandkunal,
any updates about this issue ?

**Comment by ClaytonOlleyNutrien** [comment]
We are in need of this functionality as well! @anandkunal any updates on this perchance? 😀

**Comment by ClaytonOlleyNutrien** [comment]
If anyone is still needing a solution for this you can just use the generic http provider to query the Imperva API.

`data "http" "imperva_cidrs" {
  url          = "https://my.imperva.com/api/integration/v1/ips"
  method       = "POST"
  request_body = "resp_format=json"
}
`
