### ISSUE TITLE
Add Advanced caching settings in Provider

### ISSUE THREAD

**Issue by acatte10** [imperva/terraform-provider-incapsula#35]
Hello,

It would be great to add the advanced caching settings in the Provider (like enable/disable minify css, enable/disable compress png...)

They are available here :
https://docs.imperva.com/bundle/cloud-application-security/page/api/sites-api.htm#Advanced

thanks

**Comment by joeymoore** [comment]
@acatte10 these configurations have been added in the latest provider, please reference the site configuration at https://registry.terraform.io/providers/imperva/incapsula/latest/docs/resources/site
Cheers
