### ISSUE TITLE
Importing WAF security rules does not correctly populate state

### ISSUE THREAD

**Issue by kireledan** [imperva/terraform-provider-incapsula#37]
When performing an import on `incapsula_waf_security_rule`, only the `rule_id` and `site_id` are populated within the terraform state. 

For example, when importing a rule, the resource looks like this in the terraform state.
```
    {
      "mode": "managed",
      "type": "incapsula_waf_security_rule",
      "name": "example-waf-rule-bot-access-control",
      "provider": "provider.incapsula",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "activation_mode": null,
            "block_bad_bots": null,
            "challenge_suspected_bots": null,
            "ddos_traffic_threshold": null,
            "id": "12734028/api.threats.bot_access_control",
            "rule_id": "api.threats.bot_access_control",
            "security_rule_action": null,
            "site_id": 12734028
          },
          "private": "eyJzY2hlbWFfdmVyc2lvbiI6IjAifQ=="
        }
      ]
    },
```

I assume the expected behavior is to populate the `security_rule_action` if there are any, but for the `bot_access_control`, the `block_bad_bots` and `challenge_suspected_bots` should be true or false here.

**Comment by jonDowdle** [comment]
@joeymoore We'd love to have this working and to bring our Incapsula sites under management by code. Is there anything we need to do or can help with?
