### ISSUE TITLE
Got "Invalid site cname" while using for_each to batch deploy sites.

### ISSUE THREAD

**Issue by wade-schee** [imperva/terraform-provider-incapsula#39]
I used _for_each_ to batch deploy sites after passing _incapsula_site_ a map of _csvdecode_ processed csv file.

```
locals {
  site_data = csvdecode(file(var.path))
}

resource "incapsula_site" "example-site" {
  for_each = {
    for site in local.site_data :
    site.domain => site
  }
  domain                 = each.value.domain
  account_id             = var.account
  send_site_setup_emails = "false"
  site_ip                = each.value.site_ip
  force_ssl              = each.value.force_ssl

}
```

And got error message like:

`{"res":2,"res_message":"Invalid input","debug_info":{"id-info":"13023","Invalid site` `cname":"foo.bar.com"}}`

If the site_ip column at the csv file contained either valid or invalid cname.

However, this error won't occur by neither assigning only ip addresses to the csv file at site_ip column, nor directly assigning canme address to resource section.(like site_ip="foo.bar.com" )

**Comment by anandkunal** [comment]
Hi @wade-schee, were you able to get a solution for this? You may need to contact support for this one.
