### ISSUE TITLE
is_standby flag on data centers is broken

### ISSUE THREAD

**Issue by xenalite** [imperva/terraform-provider-incapsula#41]
After recent call with Imperva support, it turns out that `is_standby` flag on data centers resource is not being correctly populated. 
```
https://www.terraform.io/docs/providers/incapsula/r/data_center.html#is_standby
```

This is because list data centers and add data centers API calls (used to set this flag) do not retrieve correct values. This leads to undefined behaviour when your resources have this flag defined, as we saw with many of our data centers turn to standby overnight. Only edit API call is able to set the standby flag correctly.

We want to continue using the provider, but cannot chance another outage due to undefined behaviour, so I propose to remove the flag until it's production ready.

**Comment by anandkunal** [comment]
HI @xenalite - I removed this functionality last week after our meeting. The change showed up in this commit - https://github.com/imperva/terraform-provider-incapsula/commit/56633b5afdbac675beecda4e01a08f5c2cc45245

Going to go ahead and close this issue out.
