### ISSUE TITLE
Cannot add custom certificate (pfx) to a site

### ISSUE THREAD

**Issue by vvigreen981** [imperva/terraform-provider-incapsula#42]
We are trying to create a site and to add a custom certificate to it. We are able to create the site but having issues adding the custom certificate.

[Provider documentation](https://www.terraform.io/docs/providers/incapsula/r/custom_certificate.html#certificate) says that "**incapsula_custom_certificate**" resource supports PFX format and that "**certificate**" argument should be "_The certificate file in base64 format_".

Here is our code:
`   provider "azurerm" {
      version = "=2.12.0"
      features {}
    }
    
    data "azurerm_key_vault_secret" "imperva_api_id" {
        name = var.imperva-api-id
        key_vault_id = var.kv.id
    }
    
    data "azurerm_key_vault_secret" "imperva_api_key" {
        name = var.imperva-api-key
        key_vault_id = var.kv.id
    }
    
    data "azurerm_key_vault_secret" "cert" {
      name = var.certificate_name
      key_vault_id = var.kv.id
    }
    
    provider "incapsula" {
      api_id = data.azurerm_key_vault_secret.imperva_api_id.value
      api_key = data.azurerm_key_vault_secret.imperva_api_key.value
    }
    
    resource "incapsula_site" "site" {
      domain = var.client_facing_fqdn
      send_site_setup_emails = true
      site_ip                = var.tm_cname
      force_ssl              = true
    }
    
    resource "incapsula_custom_certificate" "custom-certificate" {
      site_id = incapsula_site.site.id
      certificate =   filebase64("certificate.pfx")
    } `

When applying it, we get following error:

`    incapsula_custom_certificate.custom-certificate: Creating...
    
    Error: Error from Incapsula service when adding custom certificate for site_id ******807: {"res":2,"res_message":"Invalid input","debug_info":{"certificate":"invalid certificate or passphrase","id-info":"13007"}}
    
      on main.tf line 36, in resource "incapsula_custom_certificate" "custom-certificate":
      36: resource "incapsula_custom_certificate" "custom-certificate" { `

We also tried to pass the certificate in binary format as following:
`  data "local_file" "cer" {
    filename = "certificate.pfx"
}

resource "incapsula_custom_certificate" "custom-certificate" {
    site_id = incapsula_site.site.id
    certificate = data.local_file.cer.content
} `

we get similar issue:

`  Error: Error from Incapsula service when adding custom certificate for site_id *****807: {"res":2,"res_message":"Invalid input","debug_info":{"certificate":"invalid certificate or passphrase","id-info":"13017"}}

  on main.tf line 47, in resource "incapsula_custom_certificate" "custom-certificate":
  47: resource "incapsula_custom_certificate" "custom-certificate" { `

Is it something we are missing or it is an issue with provider?

**Comment by vvigreen981** [comment]
I should mention, the certificate doesn't have passphrase. 
We were able to add this certificate to the same site using direct calls to Imperva APIs in a Python script (using same Imperva API Key and ID).

**Comment by anandkunal** [comment]
Hi @vvigreen981 - this should be fixed from a commit that we pushed on June 12: https://github.com/imperva/terraform-provider-incapsula/commit/2f3e094cd22476abd758e86c0d4f144cec4c4062

Please let us know if you're still having issues.
