### ISSUE TITLE
Reqired additional resources to configure Settings and Delivery for the Site

### ISSUE THREAD

**Issue by shajinrr** [imperva/terraform-provider-incapsula#44]
We are looking for additional resources to configure Settings and Delivery for the Site.
Eg:- 
Settings -> Imperva Headers,
Delivery -> Network and REDIRECTION

Thanks
Shajin R R

**Comment by anandkunal** [comment]
Hi @shajinrr - we're currently working on delivery and performance. There are some augmentations that we've made to the API, which is why it's taking a little bit longer than anticipated. On the settings side, is there something specific you're looking to accomplish with headers?

**Comment by shajinrr** [comment]
We are to enable **INCAP-TLS-VERSION** and **INCAP-REQ-ID**

**Comment by anandkunal** [comment]
Hi @shajinrr - unfortunately, these two headers are not available to configure via the API. You'll have to use the UI for now and we'll make a request internally to add support for this. Sorry, wish I had better news. In the meantime, we were able to add in `performance` related settings in the `site` resource.
