### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by charles-muller** [imperva/terraform-provider-incapsula#47]
Are there any plans on cutting a new release of the provider? 2.1.0 was the last.

**Comment by acatte10** [comment]
hey guys, 

any idea when a new release will be done ? because lots of evol and fixes have been done since the last release in January and it's not in the provider version in Hashicorp (still in 2.1.0)  :(

thanks

**Comment by n0cturnuz** [comment]
+1

**Comment by seanmcelroy** [comment]
Looks like provider is no longer listed in the Terraform registry?
Not found with a search for Imperva, Incapsula, or WAF in https://registry.terraform.io/search/providers

However, the documentation for 2.1 appears to still be up here: https://www.terraform.io/docs/providers/incapsula/index.html

**Comment by anandkunal** [comment]
Hi there - we’re publishing to the TF registry later today (Pacific Time) from this current repository. The version will be 2.6.0. Will update this issue once this is done.

**Comment by anandkunal** [comment]
Hi there - the provider is now in the Terraform registry. You can grab the bits here: https://registry.terraform.io/providers/imperva/incapsula/latest
