### ISSUE TITLE
Unable to output the "dns_cname_record_value " when adding a site

### ISSUE THREAD

**Issue by jmeldrum76** [imperva/terraform-provider-incapsula#48]
Hi,

I am wondering if there was ever a fix for this?  What @anandkunal  stated is correct.   I would **really** like to use the native Terraform Incapsula provider.  Currently I am going to need to write a bash script to use the api  through the Terraform null_resource to remove the cancel the default ssl certificate and get the Incapsula_CNAME_Value. This is going to be a pain.

**Note**: Please see original Post for details.

**Here are a refresh of the steps to take for each site creation to workaround the issue:**

1. Run your terraform plan
2. Go into the Imperva web console, navigate to your new site's settings (Websites > your site > Settings > General), and click Cancel under the Imperva generated certificate column.
3. Run terraform refresh
4. Now you have the Incapsula_CNAME_Value that you can do something with.

Any help would be greatly appreciated.

Jeremy Meldrum

_Originally posted by @jmeldrum76 in https://github.com/imperva/terraform-provider-incapsula/issues/28#issuecomment-701079515_

**Comment by joeymoore** [comment]
@jmeldrum76 please make sure that you are using the latest TF provider (https://registry.terraform.io/providers/imperva/incapsula/latest/docs/resources/site) and ensure to use the ignore_ssl = True and you may need to use force_ssl = True depending on your site. 
Please let me know if this resolved your issue.
