### ISSUE TITLE
Parameters not being applied using incapsula_waf_security_rule provider

### ISSUE THREAD

**Issue by bb10101** [imperva/terraform-provider-incapsula#56]
Hello,
I am trying to configure several WAF exceptions using the **incapsula_waf_security_rule** provider. Most of these require parameters for both 'urls' and 'parameters'. This works for all rules IDs except "api.threats.sql_injection". When creating exceptions for this rule ID the exception is created but only configured with the URLs and ignores the parameters value. Thanks.

**Comment by bb10101** [comment]
The documentation for this provider states 'The example resources listed below include all of the supported resources for each rule_id or rule type' however this is supported/tested through the API and UI. Any help much appreciated. Thanks.

**Comment by joeymoore** [comment]
@bb10101 can you please confirm that you are using "-parallelism=1".

**Comment by bb10101** [comment]
Hi @joeymoore, I am yes. Since posting, found that "parameters" isn't stated for sqlInjectionExceptionRuleID:

https://github.com/imperva/terraform-provider-incapsula/blob/master/incapsula/resource_security_rule_exception.go#L414

I think it should be, as something like this is supported by the API:

api/prov/v1/sites/configure/whitelists?api_id=***&site_id=***&api_key=***&rule_id=api.threats.sql_injection&parameters=textbox&urls=%2Freports.aspx

**Comment by joeymoore** [comment]
@bb10101 you are correct, this is missing from the TF code:
sqlInjectionExceptionRuleID:          {"client_apps", "countries", "ips", "url_patterns", "urls"},

We will work to get this added.
Thank you

**Comment by bb10101** [comment]
Great thank you
