### ISSUE TITLE
Add support to import existing Imperva resources into Terraform

### ISSUE THREAD

**Issue by ringanta** [imperva/terraform-provider-incapsula#59]
Hi, it would be great if Imperva Terraform provider supports importing existing resources that's created via web dashboard into Terraform.
The import use case is pretty common in Terraform.
Many other providers support this out of the box.

**Comment by joeymoore** [comment]
@ringanta this import ability is possible and I believe on all the resources, just not documented.
Just use the normal import process and confirm, please let me know if a particular resource fails.
I know that site and data centers works.

**Comment by anandkunal** [comment]
Import documentation was just added to the main branch. Will be available in the `2.7.0` release.
