### ISSUE TITLE
Datacenters not updating in Imperva though Terrafrom State showing the correct value

### ISSUE THREAD

**Issue by nilvithy** [imperva/terraform-provider-incapsula#60]
When trying to update the value in datacenters "server_address" with a different value than was originally created, the value does not update in Imperva but shows as completes in terraform and shows the new value in the terraform state value.

**Comment by joeymoore** [comment]
@nilvithy are you using the incapsula_data_center_server resource? Can you share you config and does the plan show a diff/change?

**Comment by nilvithy** [comment]
After careful review of our code and syntax, and following the incapsula_data_center_server resource it was determined that we had missed out on a section to include the datacenter when creating the site and as such can mark this ticket as closed with no-fault.
