### ISSUE TITLE
incapsula_site resource log_level

### ISSUE THREAD

**Issue by smehboub** [imperva/terraform-provider-incapsula#62]
Hello,

Firstly, thank you very much for your work.
I want to share you an issue.

The incapsula_site resource sends the log_level parameter in the request body even though we don't set this parameter because the parameter is set at the resource level by default.
We get an error if we didn't activate the logs at the account or the subaccount level

**_Terraform resource_**
```
resource "incapsula_site" "project_site" {
  domain                 = "www.example.com"
  site_ip                = "X.X.X.X"
  active                 = "active"
}
```

_**Console screenshot**_
![log_level](https://raw.githubusercontent.com/smehboub/errors/master/files/imperva-log_level.png)

_**Terraform error**_
```
incapsula_site.project_site: Creating...

Error: Error from Incapsula service when updating log level for siteID ********: {"res":6001,"res_message":"Invalid configuration parameter name","debug_info":{"logs_account_id":"account is missing logs configuration","id-info":"13007"}}

  on imperva.tf line 21, in resource "incapsula_site" "project_site":
  21: resource "incapsula_site" "project_site" {
```

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by smehboub** [comment]
Fix here : https://github.com/imperva/terraform-provider-incapsula/pull/64

**Comment by anandkunal** [comment]
Merged. Thank you, @smehboub!
