### ISSUE TITLE
Need new version

### ISSUE THREAD

**Issue by smehboub** [imperva/terraform-provider-incapsula#65]
Hello @anandkunal,

As already been said, thank you very much for your work.
We are using your provider in production environment and we would need a new release with the latest code additions to take advantage of the fixes.

Could you please publish a new release ?

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by anandkunal** [comment]
Hi Sophian - sure thing. I was hoping to tie it with work around sub-accounts (I've been heads down on that over the past few days when I've had a few moments). Let me get that going now. One sec!

**Comment by smehboub-dkt** [comment]
Hi @anandkunal,

**A thousand thanks !!!**

**Comment by anandkunal** [comment]
I just bumped the release notes and make to `2.7.3`. It's making its way through the build pipeline and _should_ be available soon. I'll check back in a bit to make sure everything synced properly with the Registry. If you spot success before me, feel free to close this issue. Thanks!

**Comment by smehboub** [comment]
Ok i wouldn't hesitate.
**Many thanks for your willingness to help!!!**

**Comment by anandkunal** [comment]
Curious - it looks like GitHub actions are running slow today. The job is still marked as delayed...I'll keep an eye out for it. From a quick Google search, this has happened with GH before...first time here running into this.

**Comment by smehboub** [comment]
There is apparently an ongoing incident : https://www.githubstatus.com/history

**Comment by anandkunal** [comment]
Bummer. Well, it'll catch up at some point!

**Comment by smehboub** [comment]
I hope

**Comment by anandkunal** [comment]
Done. 2.7.3 has been published: https://registry.terraform.io/providers/imperva/incapsula/latest. Closing this out.

**Comment by smehboub** [comment]
It's very nice that you are so available, i appreciate
