### ISSUE TITLE
resource incapsula_site is failing consistently now

### ISSUE THREAD

**Issue by csbodine** [imperva/terraform-provider-incapsula#86]
I'm trying to create a basic website right now and it is failing on a consistent basis.

This is the entire resource definition: 
```
resource "incapsula_site" "site" {
  account_id = var.ACCOUNT_ID
  domain = "mydomain.com"
  naked_domain_san = false
  wildcard_san = true
  log_level = "full"
  site_ip = "myloadbalancer.com"
  domain_validation = "dns"
}
```

Which results in the error 
Error from Incapsula service when updating site for siteID xxx: {"res":3015,"res_message":"Internal error","debug_info":{"":"Add site operation hasn\u0027t finished.","id-info":"13017"}}

I enabled DEBUG logs (with private info redacted) and found the following:

2021/07/07 19:12:50 [INFO] Creating Incapsula site for domain: … timestamp=2021-07-07T19:12:50.314-0600
2021/07/07 19:12:50 [INFO] Adding Incapsula site for domain: … timestamp=2021-07-07T19:12:50.314-0600
2021/07/07 19:12:52 [DEBUG] Incapsula add site JSON response: … timestamp=2021-07-07T19:12:52.246-0600
2021/07/07 19:12:52 [INFO] Created Incapsula site for domain: … timestamp=2021-07-07T19:12:52.246-0600
2021/07/07 19:12:55 [INFO] Updating Incapsula site param (domain_validation) with value (dns) for site_id: …  timestamp=2021-07-07T19:12:55.251-0600
2021/07/07 19:12:55 [INFO] Updating Incapsula site for siteID: … timestamp=2021-07-07T19:12:55.251-0600
2021/07/07 19:12:55 [DEBUG] Incapsula update site JSON response: {"res":3015,"res_message":"Internal error","debug_info":{"":"Add site operation hasn\u0027t finished.","id-info":"13007"}}: timestamp=2021-07-07T19:12:55.874-0600
2021/07/07 19:12:55 [ERROR] Could not update Incapsula site param (domain_validation) with value (dns) for site_id: … timestamp=2021-07-07T19:12:55.874-0600

I remove the domain_validation = "dns" and it still failed with the same message on the step  [INFO] Updating Incapsula site param (site_ip) with value (…)

**Comment by joeymoore** [comment]
Can you either provide the provider version and or make sure to use the latest..
Also, if running this locally or in TFE, make sure to use --parallelism=1 in the apply command.

**Comment by csbodine** [comment]
Of course I left out the import parts!

Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.47.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/imperva/incapsula v2.7.5

I don't think I had the parallelism enabled when I captured this log, but I definitely had -parallelism=1 enabled and had the exact same result.

**Comment by joeymoore** [comment]
Please open a case with support and have them clear the state of your site with this article.
https://confluence.secure.imperva.com/display/SCW/Add+site+operation+hasn%27t+finished+-+how+to+resolve
