### ISSUE TITLE
Root resource was present, but now absent.

### ISSUE THREAD

**Issue by ksh1811** [imperva/terraform-provider-incapsula#87]
Hi, I am getting this error when running terraform apply-
it's giving error when creating this module-
module.incapsula_site.incapsula_origin_pop.origin_pop: Creating...

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ module.incapsula_site.incapsula_origin_pop.origin_pop, provider
│ "provider[\"registry.terraform.io/imperva/incapsula\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

**Comment by joeymoore** [comment]
Can you please provide the .tf file with this resource and config along with Incapsula provider version used.

**Comment by ksh1811** [comment]
> Can you please provide the .tf file with this resource and config along with Incapsula provider version used.

Sure.
This is the module with this resource-

resource "incapsula_origin_pop" "origin_pop" {
  dc_id =  incapsula_site.site.original_data_center_id
  site_id = incapsula_site.site.id
  origin_pop = var.incapsula_original_origin_pop
}

And the version is 2.8.0

**Comment by joeymoore** [comment]
Ok, for now, can you force incapsula provider version == 2.7.5 and test.
